QUESTIONS = [
"Is the Infra required as a part of Proposal?",
"Is the Infra required on On-Prem or on Cloud?",
"Is the consotium allowed for the propose solution?",
"Do we need to submit costing of proposed solution?",
"is the open source components allowed in proposed solution as per RFP?",
"In case the open source components allowed ,is it community version or enterprise Version",
"What is Technical Evaluation Criteria",
"What method of scoring will be used for evaluation of proposal",
"What is the scoring evaluation Ratio of Tech Vs Commercial ?",
"What is Client Name and Location?",
"What is the PreBid Query Submission Date?",
"What is the RFP/RFI/RFQ/RFE Submission Date",
"What is Application Response time?",
"What is Solution Uptime required as per RFP?",
"What is Project Delivery Duration?",
"How many environment is part of the proposed Solution?",
"Is support and maintanance is required for the solution",
"Is the solution require any compliance with legal and regulatory requirements, including data protection laws?",
"What are the required Document as a part of Solution",
"What is the Price to Win for RFP",
"Is there any EMD Involved in RFP?",
"If yes what is EMD Value?",
"Is there any Penalty Clause Mentioned in the RFP"
]